Service = "sif-xml2json"
Version = "v0.1.9"

[SIF]
  DefaultVer = "3.4.8"

[Loggly]
  Token = "54290728-93e0-425a-a49c-c9e834288026"

[WebService]
  Port = 1324

[Route]
  Convert = "/sif-xml2json/convert"
  Help = "/"

[NATS]
  Subject = "SIF-XML2JSON"
  Timeout = 500
  URL = "nats://192.168.78.130:4222"

